# This file was generated by liblab | https://liblab.com/

from ring_central import RingCentral, Environment

sdk = RingCentral(access_token="YOUR_ACCESS_TOKEN", base_url=Environment.DEFAULT.value)

result = sdk.webinar_subscriptions.rcw_n11s_list_subscriptions()

print(result)
