# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({"bridge_id": "bridgeId"})
class BridgePinsWithoutPstn(BaseModel):
    """BridgePinsWithoutPstn

    :param bridge_id: Bridge identifier, defaults to None
    :type bridge_id: str, optional
    :param web: Bridge short identifier (Web PIN). The digital unique code which is used to join to a meeting. If it is not specified while creation, then a code will be generated. If it is a default bridge, then this code is Personal Meeting Identifier (PMI). NOTE: Changing this PIN via update method is deprecated. So to change Web PIN use the method: ```*[PATCH] /rcvideo/v2/bridges/bridgeId/pin/web*``` , defaults to None
    :type web: str, optional
    """

    def __init__(self, bridge_id: str = None, web: str = None):
        if bridge_id is not None:
            self.bridge_id = bridge_id
        if web is not None:
            self.web = web
