# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({"keep_assets_in_inventory": "keepAssetsInInventory"})
class RemoveLineRequest(BaseModel):
    """RemoveLineRequest

    :param keep_assets_in_inventory: The flag that controls what to do with the number and device: - if the value of `keepAssetsInInventory` is `true`, the given device is moved to unassigned devices and the number is moved to the number inventory; - if the value of `keepAssetsInInventory` is `false`, the given device and number is removed from the account; - if the parameter `keepAssetsInInventory` is not set (empty body) or the value of the parameter is empty, default value `true` is set.
    :type keep_assets_in_inventory: bool
    """

    def __init__(self, keep_assets_in_inventory: bool):
        self.keep_assets_in_inventory = keep_assets_in_inventory
